# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby "2.6.6"

gem 'open-uri'
gem 'nokogiri', '0.10.10'
gem 'json', '2.1.0'
gem 'pry', '0.14.1'
gem 'csv', '3.0.9'
gem 'zip', '2.0.2'
gem 'pony', '1.13.1'